services:
  - type: web
    name: gokuhitter-bot
    env: python
    buildCommand: "bash build.sh"
    startCommand: "python bot.py"
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: LOG_GROUP_ID
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: PYTHON_VERSION
        value: 3.11.9
